/*global systemDictionary:true */
'use strict';
systemDictionary = {
    'mercury adapter':                                                                {
        'en':    'Adapter settings for mercury',
        'de':    'Adaptereinstellungen für mercury',
        'ru':    'Настройки адаптера mercury',
        'pt':    'Configurações do adaptador para mercury',
        'nl':    'Adapterinstellingen voor mercury',
        'fr':    "Paramètres d'adaptateur pour mercury",
        'it':    "Impostazioni dell'adattatore per mercury",
        'es':    'Ajustes del adaptador para mercury',
        'pl':    'Ustawienia adaptera dla mercury',
        'zh-cn': 'mercury的适配器设置'
    },
    'devices':                                                                        {
        'en':    'Devices',
        'de':    'Geräte',
        'ru':    'Устройства',
        'pt':    'Dispositivos',
        'nl':    'Apparaten',
        'fr':    'Dispositifs',
        'it':    'Dispositivi',
        'es':    'Seadmed',
        'pl':    'Urządzenia',
        'zh-cn': '设备'
    },
    'settings':                                                                       {
        'en':    'Settings',
        'de':    'die Einstellungen',
        'ru':    'Настройки',
        'pt':    'Configurações',
        'nl':    'Instellingen',
        'fr':    'Réglages',
        'it':    'Impostazioni',
        'es':    'Seadistused',
        'pl':    'Ustawienia',
        'zh-cn': '设定值'
    },
    'typeconnect':                                                                    {
        'en':    'Connection type',
        'de':    'Verbindungstyp',
        'ru':    'Тип соединения',
        'pt':    'Tipo de conexão',
        'nl':    'Connectie type',
        'fr':    'Type de connexion',
        'it':    'Tipo di connessione',
        'es':    'ühenduse tüüp',
        'pl':    'Rodzaj połączenia',
        'zh-cn': '连接类型'
    },
    'ip':                                                                             {
        'en':    'IP-address',
        'de':    'IP-adrese',
        'ru':    'IP-адрес',
        'pt':    'IP-endereço ',
        'nl':    'IP-adresse',
        'fr':    'IP-adresse',
        'it':    'IP-indirizzo',
        'es':    'IP-aadress',
        'pl':    'IP-adres',
        'zh-cn': 'IP-地址'
    },
    'tcpport':                                                                        {
        'en':    'Port',
        'de':    'Hafen',
        'ru':    'Порт',
        'pt':    'Porta',
        'nl':    'Port',
        'fr':    'Port',
        'it':    'Porto',
        'es':    'Port',
        'pl':    'Port',
        'zh-cn': '端口'
    },
    'tcp':                                                                            {
        'en':    'TCP/IP',
        'de':    'TCP/IP',
        'ru':    'TCP/IP',
        'pt':    'TCP/IP',
        'nl':    'TCP/IP',
        'fr':    'TCP/IP',
        'it':    'TCP/IP',
        'es':    'TCP/IP',
        'pl':    'TCP/IP',
        'zh-cn': 'TCP/IP'
    },
    'usb':                                                                            {
        'en':    'USB/COM',
        'de':    'USB/COM',
        'ru':    'USB/COM',
        'pt':    'USB/COM',
        'nl':    'USB/COM',
        'fr':    'USB/COM',
        'it':    'USB/COM',
        'es':    'USB/COM',
        'pl':    'USB/COM',
        'zh-cn': 'USB/COM'
    },
    'baud':                                                                           {
        'en':    'Baudrate',
        'de':    'Datenrate',
        'ru':    'Скорость передачи данных',
        'pt':    'Taxa de dados',
        'nl':    'Gegevenssnelheid',
        'fr':    'Débit de données',
        'it':    'Velocità dei dati',
        'es':    'Andmekiirus',
        'pl':    'Szybkość transmisji danych',
        'zh-cn': '资料速率'
    },
    'usbport':                                                                        {
        'en':    'COM-Port',
        'de':    'COM-Hafen',
        'ru':    'COM-Порт',
        'pt':    'COM-Porta',
        'nl':    'COM-Port',
        'fr':    'COM-Port',
        'it':    'COM-Porto',
        'es':    'COM-Port',
        'pl':    'COM-Port',
        'zh-cn': 'COM-端口'
    },
    'parity':                                                                         {
        'en':    'Parity',
        'de':    'Parität',
        'ru':    'Четность',
        'pt':    'Paridade',
        'nl':    'Pariteit',
        'fr':    'La parité',
        'it':    'Parità',
        'es':    'Pariteet',
        'pl':    'Parzystość',
        'zh-cn': '平价'
    },
    'timeoutresponse':                                                                {
        'en':    'Response Timeout (ms)',
        'de':    'Antwortzeitlimit (ms)',
        'ru':    'Время ожидания ответа (мс)',
        'pt':    'Tempo limite de resposta (ms)',
        'nl':    'Time-out van reactie (ms)',
        'fr':    'Délai de réponse (ms)',
        'it':    'Timeout di risposta (ms)',
        'es':    'Vastuse aegumine (ms)',
        'pl':    'Limit czasu odpowiedzi (ms)',
        'zh-cn': '响应超时 (ms)'
    },
    'systemtimeout':                                                                  {
        'en':    'System Timeout (ms)',
        'de':    'System-Timeout (ms)',
        'ru':    'Системный таймаут (мс)',
        'pt':    'Tempo limite de resposta (ms)',
        'nl':    'Systeemtime-out (ms)',
        'fr':    'Délai d\'expiration du système (ms)',
        'it':    'Timeout del sistema (ms)',
        'es':    'Süsteemi aegumine (ms)',
        'pl':    'Limit czasu systemu (ms)',
        'zh-cn': '系统超时 (ms)'
    },
    'factortimeout':                                                                  {
        'en':    'System tmeout multiplier',
        'de':    'System timeout multiplikator',
        'ru':    'Множитель системного таймаута',
        'pt':    'Multiplicador de tempo limite do sistema',
        'nl':    'System timeout multiplier',
        'fr':    'Multiplicateur de délai d\'expiration du système',
        'it':    'Moltiplicatore del timeout di sistema',
        'es':    'Süsteemi ajalõpu kordaja',
        'pl':    'Mnożnik limitu czasu systemu',
        'zh-cn': '系统超时倍增器'
    },
    'model':                                                                          {
        'en':    'Counter model',
        'de':    'Gegenmodell',
        'ru':    'Модель счетчика',
        'pt':    'Modelo de contador',
        'nl':    'Teller model',
        'fr':    'Modèle de compteur',
        'it':    'Contatore modello',
        'es':    'Loendurimudel',
        'pl':    'Model licznika',
        'zh-cn': '柜台型号'
    },
    'address':                                                                        {
        'en':    'Counter network address',
        'de':    'Zählernetzwerkadresse',
        'ru':    'Сетевой адрес счетчика',
        'pt':    'Endereço de rede do contador',
        'nl':    'Teller netwerkadres',
        'fr':    'Adresse réseau du compteur',
        'it':    'Contatore dell\'indirizzo di rete',
        'es':    'Loenduri võrgu aadress',
        'pl':    'Licznik adresu sieciowego',
        'zh-cn': '柜台网络地址'
    },
    'user':                                                                           {
        'en':    'User',
        'de':    'Benutzer',
        'ru':    'Пользователь',
        'pt':    'Usuário',
        'nl':    'Gebruiker',
        'fr':    'Utilisateur',
        'it':    'Utente',
        'es':    'Kasutaja',
        'pl':    'Użytkownik',
        'zh-cn': '用户名'
    },
    'admin':                                                                          {
        'en':    'Administrator',
        'de':    'Admin',
        'ru':    'Администратор',
        'pt':    'Admin',
        'nl':    'Admin',
        'fr':    'Admin',
        'it':    'Amministratore',
        'es':    'Administraator',
        'pl':    'Administrator',
        'zh-cn': '管理员'
    },
    'password':                                                                       {
        'en':    'Password',
        'de':    'Passwort',
        'ru':    'Пароль',
        'pt':    'Senha',
        'nl':    'Wachtwoord',
        'fr':    'Mot de passe',
        'it':    'Password',
        'es':    'Parool',
        'pl':    'Hasło',
        'zh-cn': '密码'
    },
    'name':                                                                           {
        'en':    'Name',
        'de':    'Vorname',
        'ru':    'Имя',
        'pt':    'Primeiro nome',
        'nl':    'Voornaam',
        'fr':    'Prénom',
        'it':    'Nome',
        'es':    'Eesnimi',
        'pl':    'Imię',
        'zh-cn': '名'
    },
    'cancel':                                                                         {
        'en':    'Cancel',
        'de':    'Abbrechen',
        'ru':    'Отмена',
        'pt':    'Cancelar',
        'nl':    'Annuleren',
        'fr':    'Annuler',
        'it':    'cancellazione',
        'es':    'Tühista',
        'pl':    'Anuluj',
        'zh-cn': '取消'
    },
    'agree':                                                                          {
        'en':    'OK',
        'de':    'OK',
        'ru':    'OK',
        'pt':    'OK',
        'nl':    'OK',
        'fr':    'OK',
        'it':    'OK',
        'es':    'OK',
        'pl':    'OK',
        'zh-cn': 'OK'
    },
    'find':                                                                           {
        'en':    'Find',
        'de':    'Zu finden',
        'ru':    'Найти',
        'pt':    'Para encontrar',
        'nl':    'Te vinden',
        'fr':    'Pour trouver',
        'it':    'Da trovare',
        'es':    'Et leida',
        'pl':    'Znaleźć',
        'zh-cn': '寻找'
    },
    'info':                                                                           {
        'en':    'Information',
        'de':    'Informationen',
        'ru':    'Информация',
        'pt':    'Informação',
        'nl':    'Informatie',
        'fr':    'L\'information',
        'it':    'Informazioni',
        'es':    'Teave',
        'pl':    'Informacja',
        'zh-cn': '资讯中心'
    },
    'input addres or sn':                                                             {
        'en':    'Enter counter address or serial number',
        'de':    'Geben Sie die Zähleradresse oder Seriennummer ein',
        'ru':    'Введите адрес или серийный номер счетчика',
        'pt':    'Digite o endereço do contador ou o número de série',
        'nl':    'Voer telleradres of serienummer in',
        'fr':    'Entrez l\'adresse du compteur ou le numéro de série',
        'it':    'Immettere l\'indirizzo del contatore o il numero di serie',
        'es':    'Sisestage loenduri aadress või seerianumber',
        'pl':    'Wpisz adres licznika lub numer seryjny',
        'zh-cn': '输入柜台地址或序列号'
    },
    'add counter':                                                                    {
        'en':    'Add counter',
        'de':    'Zähler hinzufügen',
        'ru':    'Добавить счетчик',
        'pt':    'Adicionar contador',
        'nl':    'Teller toevoegen',
        'fr':    'Ajouter un compteur',
        'it':    'Aggiungi contatore',
        'es':    'Lisage loendur',
        'pl':    'Dodaj licznik',
        'zh-cn': '添加柜台'
    },
    'Error':                                                                          {
        'en':    'Error',
        'de':    'Fehler',
        'ru':    'Ошибка',
        'pt':    'Erro',
        'nl':    'Fout',
        'fr':    'Erreur',
        'it':    'Errore',
        'es':    'Viga',
        'pl':    'Błąd',
        'zh-cn': '失误'
    },
    'extended':                                                                       {
        'en':    'Extended Answer Mode',
        'de':    'Erweiterter Antwortmodus',
        'ru':    'Расширенный режим ответа',
        'pt':    'Modo de resposta estendida',
        'nl':    'Uitgebreide antwoordmodus',
        'fr':    'Mode de réponse étendu',
        'it':    'Modalità di risposta estesa',
        'es':    'Laiendatud vastuse režiim',
        'pl':    'Tryb rozszerzonej odpowiedzi',
        'zh-cn': '扩展应答模式'
    },
    'addres or sn':                                                                   {
        'en':    'Address or Serial Number',
        'de':    'Adresse oder Seriennummer',
        'ru':    'Адрес или серийный номер',
        'pt':    'Endereço ou número de série',
        'nl':    'Adres of serienummer',
        'fr':    'Adresse ou numéro de série',
        'it':    'Indirizzo o numero di serie',
        'es':    'Aadress või seerianumber',
        'pl':    'Adres lub numer seryjny',
        'zh-cn': '地址或序列号'
    },
    'slowPollingTime':                                                                    {
        'en':    'Polling period of non-main parameters (ms)',
        'de':    'Der Zeitraum der Umfrage ist nicht der Hauptparameter (ms)',
        'ru':    'Интервал между опросом не основных параметров (мс)',
        'pt':    'Período de votação de parâmetros não principais (ms)',
        'nl':    'De periode van de enquête is niet de belangrijkste parameter (ms)',
        'fr':    'La période de l\'enquête n\'est pas les principaux paramètres (ms)',
        'it':    'Il periodo del sondaggio non è i parametri principali (ms)',
        'es':    'Uuringu periood ei ole peamised parameetrid (ms)',
        'pl':    'Okres badania nie jest głównymi parametrami (ms)',
        'zh-cn': '调查期不是主要参数 (ms)'
    },
    'fastPollingTime':                                                                    {
        'en':    'Polling period main parameters (ms)',
        'de':    'Der Erhebungszeitraum der Hauptparameter (ms)',
        'ru':    'Интервал между опросом основных параметров (мс)',
        'pt':    'O período da pesquisa dos principais parâmetros (ms)',
        'nl':    'De onderzoeksperiode van de belangrijkste parameters (ms)',
        'fr':    'La période d\'enquête des principaux paramètres (ms)',
        'it':    'Il periodo di rilevamento dei parametri principali (ms)',
        'es':    'Peamiste parameetrite vaatlusperiood (ms)',
        'pl':    'Okres badania głównych parametrów (ms)',
        'zh-cn': '调查期主要参数 (ms)'
    },
    'delete the device':                                                              {
        'en':    'Are you sure you want to delete the device?',
        'de':    'Möchten Sie das Gerät wirklich löschen?',
        'ru':    'Вы действительно хотите удалить устройство?',
        'pt':    'Tem certeza de que deseja excluir o dispositivo?',
        'nl':    'Weet je zeker dat je het apparaat wilt verwijderen?',
        'fr':    'Voulez-vous vraiment supprimer le périphérique?',
        'it':    'Sei sicuro di voler eliminare il dispositivo?',
        'es':    'Kas soovite kindlasti seadme kustutada?',
        'pl':    'Czy na pewno chcesz usunąć urządzenie?',
        'zh-cn': '调查期主要参数'
    },
    'counter card settings':                                                          {
        'en':    'Counter Card Settings',
        'de':    'Zählerkarteneinstellungen',
        'ru':    'Настройки карточки счетчика',
        'pt':    'Configurações do cartão do contador',
        'nl':    'Teller kaartinstellingen',
        'fr':    'Paramètres de la carte de compteur',
        'it':    'Impostazioni della carta contatore',
        'es':    'Loenduri kaardi seaded',
        'pl':    'Ustawienia karty licznika',
        'zh-cn': '柜台卡设置'
    },
    'driver is not running':                                                          {
        'en':    'The driver is not running, first run the driver',
        'de':    'Der Treiber wird nicht ausgeführt. Führen Sie zuerst den Treiber aus',
        'ru':    'Драйвер не запущен, сначала запустите драйвер',
        'pt':    'O driver não está sendo executado, primeiro execute o driver',
        'nl':    'De driver draait niet, voer eerst de driver uit',
        'fr':    'Le pilote ne fonctionne pas, exécutez d\'abord le pilote',
        'it':    'Il driver non è in esecuzione, eseguire prima il driver',
        'es':    'Juht ei tööta, kõigepealt käivitage juht',
        'pl':    'Sterownik nie działa, najpierw uruchom sterownik',
        'zh-cn': '驱动程序未运行，请先运行驱动程序'
    },
    'No response, retry the request':                                                 {
        'en':    'No response, retry the request',
        'de':    'Keine Antwort, wiederholen Sie die Anfrage',
        'ru':    'Нет ответа, повторите запрос',
        'pt':    'Sem resposta, tente novamente a solicitação',
        'nl':    'Geen antwoord, probeer het opnieuw',
        'fr':    'Aucune réponse, réessayez la demande',
        'it':    'Nessuna risposta, ritentare la richiesta',
        'es':    'Vastus puudub, proovige taotlust uuesti',
        'pl':    'Brak odpowiedzi, spróbuj ponownie',
        'zh-cn': '无回应，请重试请求'
    },
    'Error opening communication channel':                                            {
        'en':    'Error opening communication channel',
        'de':    'Fehler beim Öffnen des Kommunikationskanals',
        'ru':    'Ошибка отрытия канала связи',
        'pt':    'Erro ao abrir o canal de comunicação',
        'nl':    'Fout bij openen van communicatiekanaal',
        'fr':    'Erreur lors de l\'ouverture du canal de communication',
        'it':    'Errore durante l\'apertura del canale di comunicazione',
        'es':    'Viga suhtluskanali avamisel',
        'pl':    'Błąd podczas otwierania kanału komunikacji',
        'zh-cn': '打开通讯通道时出错'
    },
    'Invalid data specified':                                                         {
        'en':    'Invalid data specified',
        'de':    'Ungültige Daten angegeben',
        'ru':    'Заданы не корректные данные',
        'pt':    'Dados inválidos especificados',
        'nl':    'Ongeldige gegevens opgegeven',
        'fr':    'Données non valides spécifiées',
        'it':    'Dati specificati non validi',
        'es':    'Täpsustatud on valed andmed',
        'pl':    'Podano nieprawidłowe dane',
        'zh-cn': '指定的数据无效'
    },
    'No response':                                                                    {
        'en':    'No response from the counter',
        'de':    'Keine Antwort vom Zähler',
        'ru':    'Нет ответа от счетчика',
        'pt':    'Nenhuma resposta do contador',
        'nl':    'Geen reactie van de balie',
        'fr':    'Pas de réponse du compteur',
        'it':    'Nessuna risposta dal contatore',
        'es':    'Letilt ei tulnud mingit vastust',
        'pl':    'Brak odpowiedzi z lady',
        'zh-cn': '柜台没有回应'
    },
    'CRC Error':                                                                      {
        'en':    'CRC Error',
        'de':    'Prüfsummenfehler CRC',
        'ru':    'Ошибка котнтрольной суммы CRC',
        'pt':    'Erro de soma de verificação CRC',
        'nl':    'Checksum-fout CRC',
        'fr':    'Erreur de somme de contrôle CRC',
        'it':    'Errore di checksum CRC',
        'es':    'Kontrollsumma viga CRC',
        'pl':    'Błąd sumy kontrolnej CRC',
        'zh-cn': '校验和错误 CRC'
    },
    'Location':                                                                       {
        'en':    'Location',
        'de':    'Lage',
        'ru':    'Местоположение',
        'pt':    'Localização',
        'nl':    'Locatie',
        'fr':    'Emplacement',
        'it':    'Posizione',
        'es':    'Asukoht',
        'pl':    'Lokalizacja',
        'zh-cn': '所在位置'
    },
    'Serial number':                                                                  {
        'en':    'Serial number',
        'de':    'Seriennummer',
        'ru':    'Серийный номер',
        'pt':    'Número de série',
        'nl':    'Serienummer',
        'fr':    'Numéro de série',
        'it':    'Numero di serie',
        'es':    'Seerianumber',
        'pl':    'Numer seryjny',
        'zh-cn': '序列号'
    },
    'Production date':                                                                {
        'en':    'Production date',
        'de':    'Produktionsdatum',
        'ru':    'Дата изготовления',
        'pt':    'Data de produção',
        'nl':    'Productiedatum',
        'fr':    'Date de production',
        'it':    'Data di produzione',
        'es':    'Tootmise kuupäev',
        'pl':    'Data produkcji',
        'zh-cn': '生产日期'
    },
    'Software version':                                                               {
        'en':    'Software version',
        'de':    'Softwareversion',
        'ru':    'Версия ПО',
        'pt':    'Versão do software',
        'nl':    'Softwareversie',
        'fr':    'Version du logiciel',
        'it':    'Versione del software',
        'es':    'Tarkvara versioon',
        'pl':    'Wersja oprogramowania',
        'zh-cn': '软件版本'
    },
    'Everything is fine':                                                             {
        'en':    'Everything is fine',
        'de':    'Alles ist normal',
        'ru':    'Всё в норме',
        'pt':    'Está tudo normal',
        'nl':    'Alles is normaal',
        'fr':    'Tout est normal',
        'it':    'È tutto normale',
        'es':    'Kõik on normaalne',
        'pl':    'Wszystko jest normalne',
        'zh-cn': '一切正常'
    },
    'Invalid command or parameter':                                                   {
        'en':    'Invalid command or parameter',
        'de':    'Ungültiger Befehl oder Parameter',
        'ru':    'Недопустимая команда или параметр',
        'pt':    'Comando ou parâmetro inválido',
        'nl':    'Ongeldige opdracht of parameter',
        'fr':    'Commande ou paramètre non valide',
        'it':    'Comando o parametro non valido',
        'es':    'Kehtetu käsk või parameeter',
        'pl':    'Niepoprawne polecenie lub parametr',
        'zh-cn': '无效的命令或参数'
    },
    'Not enough level to satisfy request':                                            {
        'en':    'Not enough level to satisfy request',
        'de':    'Nicht genug Level, um die Anfrage zu erfüllen',
        'ru':    'Недостаточен уровень для удовлетворения запроса',
        'pt':    'Nível insuficiente para atender à solicitação',
        'nl':    'Onvoldoende niveau om aan verzoek te voldoen',
        'fr':    'Niveau insuffisant pour répondre à la demande',
        'it':    'Livello insufficiente per soddisfare la richiesta',
        'es':    'Taotluse rahuldamiseks pole piisavalt taset',
        'pl':    'Poziom niewystarczający do spełnienia żądania',
        'zh-cn': '等级不足，无法满足要求'
    },
    'The counters internal clock has already been adjusted during the current day.': {
        'en':    'The counter’s internal clock has already been adjusted during the current day',
        'de':    'Die interne Uhr des Zählers wurde bereits am aktuellen Tag eingestellt',
        'ru':    'Внутренние часы счетчика уже корректировались в течение текущих суток',
        'pt':    'O relógio interno do contador já foi ajustado durante o dia atual.',
        'nl':    'De interne klok van de teller is al aangepast tijdens de huidige dag',
        'fr':    'L\'horloge interne du compteur a déjà été ajustée au cours de la journée en cours.',
        'it':    'L\'orologio interno del contatore è già stato regolato durante il giorno corrente.',
        'es':    'Loenduri sisemine kell on praeguse päeva jooksul juba reguleeritud.',
        'pl':    'Wewnętrzny zegar licznika został już wyregulowany w bieżącym dniu.',
        'zh-cn': '该计数器的内部时钟已在当天调整。'
    },
    'Communication channel not open, try again later':                                {
        'en':    'Communication channel not open, try again later',
        'de':    'Kommunikationskanal nicht geöffnet, versuchen Sie es später erneut',
        'ru':    'Не открыт канал связи, повторите попытку позже',
        'pt':    'Canal de comunicação não aberto, tente novamente mais tarde',
        'nl':    'Communicatiekanaal niet geopend, probeer het later opnieuw',
        'fr':    'Le canal de communication n\'est pas ouvert, réessayez plus tard',
        'it':    'Canale di comunicazione non aperto, riprovare più tardi',
        'es':    'Sidekanal pole avatud, proovige hiljem uuesti',
        'pl':    'Kanał komunikacji nie jest otwarty, spróbuj ponownie później',
        'zh-cn': '通讯渠道未打开，请稍后再试'
    },
    'CRC16 software':                                                                 {
        'en':    'CRC16 software',
        'de':    'CRC16 Gerätesoftware',
        'ru':    'CRC16 ПО прибора',
        'pt':    'CRC16 Software do dispositivo',
        'nl':    'CRC16 Apparaatsoftware',
        'fr':    'CRC16 Logiciel de l\'appareil',
        'it':    'CRC16 Software del dispositivo',
        'es':    'CRC16 Seadme tarkvara',
        'pl':    'CRC16 Oprogramowanie urządzenia',
        'zh-cn': 'CRC16 设备软件'
    },
    'Energy Class A+':                                                                {
        'en':    'Energy Class A+',
        'de':    'Energieklasse A+',
        'ru':    'Класс энергии A+',
        'pt':    'Classe energética A+',
        'nl':    'Energieklasse A+',
        'fr':    'Classe énergétique A+',
        'it':    'Classe energetica A+',
        'es':    'Energiaklass A+',
        'pl':    'Klasa energetyczna A+',
        'zh-cn': '能源等级 A+'
    },
    'Energy Class R+':                                                                {
        'en':    'Energy Class R+',
        'de':    'Energy Class R+',
        'ru':    'Класс энергии R+',
        'pt':    'Energy Class R+',
        'nl':    'Energy Class R+',
        'fr':    'Energy Class R+',
        'es':    'Energy Class R+',
        'pl':    'Energy Class R+',
        'it':    'Energy Class R+',
        'zh-cn': 'Energy Class R+'
    },
    'Rated voltage':                                                                  {
        'en':    'Rated voltage',
        'de':    'Rated voltage',
        'ru':    'Номинальное напряжение',
        'pt':    'Rated voltage',
        'nl':    'Rated voltage',
        'fr':    'Rated voltage',
        'es':    'Rated voltage',
        'pl':    'Rated voltage',
        'it':    'Rated voltage',
        'zh-cn': 'Rated voltage'
    },
    'Rated current':                                                                  {
        'en':    'Rated current',
        'de':    'Rated current',
        'ru':    'Номинальный ток',
        'pt':    'Rated current',
        'nl':    'Rated current',
        'fr':    'Rated current',
        'es':    'Rated current',
        'pl':    'Rated current',
        'it':    'Rated current',
        'zh-cn': 'Rated current'
    },
    'Number of destinations':                                                         {
        'en':    'Number of destinations',
        'de':    'Number of destinations',
        'ru':    'Число направлений',
        'pt':    'Number of destinations',
        'nl':    'Number of destinations',
        'fr':    'Number of destinations',
        'es':    'Number of destinations',
        'pl':    'Number of destinations',
        'it':    'Number of destinations',
        'zh-cn': 'Number of destinations'
    },
    'Temperature Range':                                                              {
        'en':    'Temperature Range',
        'de':    'Temperature Range',
        'ru':    'Температурный диапазон',
        'pt':    'Temperature Range',
        'nl':    'Temperature Range',
        'fr':    'Temperature Range',
        'es':    'Temperature Range',
        'pl':    'Temperature Range',
        'it':    'Temperature Range',
        'zh-cn': 'Temperature Range'
    },
    'Medium Capacity Profile capacities':                                             {
        'en':    'Medium Capacity Profile capacities',
        'de':    'Medium Capacity Profile capacities',
        'ru':    'Учет профиля сред. мощностей',
        'pt':    'Medium Capacity Profile capacities',
        'nl':    'Medium Capacity Profile capacities',
        'fr':    'Medium Capacity Profile capacities',
        'es':    'Medium Capacity Profile capacities',
        'pl':    'Medium Capacity Profile capacities',
        'it':    'Medium Capacity Profile capacities',
        'zh-cn': 'Medium Capacity Profile capacities'
    },
    'Number of phases':                                                               {
        'en':    'Number of phases',
        'de':    'Number of phases',
        'ru':    'Число фаз',
        'pt':    'Number of phases',
        'nl':    'Number of phases',
        'fr':    'Number of phases',
        'es':    'Number of phases',
        'pl':    'Number of phases',
        'it':    'Number of phases',
        'zh-cn': 'Number of phases'
    },
    'Counter constant':                                                               {
        'en':    'Counter constant',
        'de':    'Counter constant',
        'ru':    'Постоянная счетчика',
        'pt':    'Counter constant',
        'nl':    'Counter constant',
        'fr':    'Counter constant',
        'es':    'Counter constant',
        'pl':    'Counter constant',
        'it':    'Counter constant',
        'zh-cn': 'Counter constant'
    },
    'Phase Summation':                                                                {
        'en':    'Phase Summation',
        'de':    'Phase Summation',
        'ru':    'Суммирование фаз',
        'pt':    'Phase Summation',
        'nl':    'Phase Summation',
        'fr':    'Phase Summation',
        'es':    'Phase Summation',
        'pl':    'Phase Summation',
        'it':    'Phase Summation',
        'zh-cn': 'Phase Summation'
    },
    'Tariff':                                                                         {
        'en':    'Tariff',
        'de':    'Tariff',
        'ru':    'Тарификатор',
        'pt':    'Tariff',
        'nl':    'Tariff',
        'fr':    'Tariff',
        'es':    'Tariff',
        'pl':    'Tariff',
        'it':    'Tariff',
        'zh-cn': 'Tariff'
    },
    'Counter type':                                                                   {
        'en':    'Counter type',
        'de':    'Counter type',
        'ru':    'Тип счетчика',
        'pt':    'Counter type',
        'nl':    'Counter type',
        'fr':    'Counter type',
        'es':    'Counter type',
        'pl':    'Counter type',
        'it':    'Counter type',
        'zh-cn': 'Counter type'
    },
    'Execution option':                                                               {
        'en':    'Execution option',
        'de':    'Execution option',
        'ru':    'Вариант исполнения',
        'pt':    'Execution option',
        'nl':    'Execution option',
        'fr':    'Execution option',
        'es':    'Execution option',
        'pl':    'Execution option',
        'it':    'Execution option',
        'zh-cn': 'Execution option'
    },
    'Memory':                                                                         {
        'en':    'Memory',
        'de':    'Memory',
        'ru':    'Объем памяти',
        'pt':    'Memory',
        'nl':    'Memory',
        'fr':    'Memory',
        'es':    'Memory',
        'pl':    'Memory',
        'it':    'Memory',
        'zh-cn': 'Memory'
    },
    'Built-in PLM Modem':                                                             {
        'en':    'Built-in PLM Modem',
        'de':    'Built-in PLM Modem',
        'ru':    'Встроенный модем PLM',
        'pt':    'Built-in PLM Modem',
        'nl':    'Built-in PLM Modem',
        'fr':    'Built-in PLM Modem',
        'es':    'Built-in PLM Modem',
        'pl':    'Built-in PLM Modem',
        'it':    'Built-in PLM Modem',
        'zh-cn': 'Built-in PLM Modem'
    },
    'Built in GSM Modem':                                                             {
        'en':    'Built in GSM Modem',
        'de':    'Built in GSM Modem',
        'ru':    'Встроенный модем GSM',
        'pt':    'Built in GSM Modem',
        'nl':    'Built in GSM Modem',
        'fr':    'Built in GSM Modem',
        'es':    'Built in GSM Modem',
        'pl':    'Built in GSM Modem',
        'it':    'Built in GSM Modem',
        'zh-cn': 'Built in GSM Modem'
    },
    'Optical port':                                                                   {
        'en':    'Optical port',
        'de':    'Optical port',
        'ru':    'Оптопорт',
        'pt':    'Optical port',
        'nl':    'Optical port',
        'fr':    'Optical port',
        'es':    'Optical port',
        'pl':    'Optical port',
        'it':    'Optical port',
        'zh-cn': 'Optical port'
    },
    'Interface type':                                                                 {
        'en':    'Interface type',
        'de':    'Interface type',
        'ru':    'Тип интерфейса',
        'pt':    'Interface type',
        'nl':    'Interface type',
        'fr':    'Interface type',
        'es':    'Interface type',
        'pl':    'Interface type',
        'it':    'Interface type',
        'zh-cn': 'Interface type'
    },
    'External power':                                                                 {
        'en':    'External power',
        'de':    'External power',
        'ru':    'Внешнее питание',
        'pt':    'External power',
        'nl':    'External power',
        'fr':    'External power',
        'es':    'External power',
        'pl':    'External power',
        'it':    'External power',
        'zh-cn': 'External power'
    },
    'Top Seal Electronic Seal':                                                       {
        'en':    'Top Seal Electronic Seal',
        'de':    'Top Seal Electronic Seal',
        'ru':    'Элект. пломба верх. крышки',
        'pt':    'Top Seal Electronic Seal',
        'nl':    'Top Seal Electronic Seal',
        'fr':    'Top Seal Electronic Seal',
        'es':    'Top Seal Electronic Seal',
        'pl':    'Top Seal Electronic Seal',
        'it':    'Top Seal Electronic Seal',
        'zh-cn': 'Top Seal Electronic Seal'
    },
    'Built-in load shedding relay':                                                   {
        'en':    'Built-in load shedding relay',
        'de':    'Built-in load shedding relay',
        'ru':    'Встроен. реле отключ. нагруз.',
        'pt':    'Built-in load shedding relay',
        'nl':    'Built-in load shedding relay',
        'fr':    'Built-in load shedding relay',
        'es':    'Built-in load shedding relay',
        'pl':    'Built-in load shedding relay',
        'it':    'Built-in load shedding relay',
        'zh-cn': 'Built-in load shedding relay'
    },
    'LCD backlight':                                                                  {
        'en':    'LCD backlight',
        'de':    'LCD backlight',
        'ru':    'Подсветка ЖКИ',
        'pt':    'LCD backlight',
        'nl':    'LCD backlight',
        'fr':    'LCD backlight',
        'es':    'LCD backlight',
        'pl':    'LCD backlight',
        'it':    'LCD backlight',
        'zh-cn': 'LCD backlight'
    },
    'Tariff metering of maximum power':                                               {
        'en':    'Tariff metering of maximum power',
        'de':    'Tariff metering of maximum power',
        'ru':    'Потариф. учет макс. мощности',
        'pt':    'Tariff metering of maximum power',
        'nl':    'Tariff metering of maximum power',
        'fr':    'Tariff metering of maximum power',
        'es':    'Tariff metering of maximum power',
        'pl':    'Tariff metering of maximum power',
        'it':    'Tariff metering of maximum power',
        'zh-cn': 'Tariff metering of maximum power'
    },
    'Electronic seal of protective cover':                                            {
        'en':    'Electronic seal of protective cover',
        'de':    'Electronic seal of protective cover',
        'ru':    'Элект. пломба защит. крышки',
        'pt':    'Electronic seal of protective cover',
        'nl':    'Electronic seal of protective cover',
        'fr':    'Electronic seal of protective cover',
        'es':    'Electronic seal of protective cover',
        'pl':    'Electronic seal of protective cover',
        'it':    'Electronic seal of protective cover',
        'zh-cn': 'Electronic seal of protective cover'
    },
    'Interface2':                                                                     {
        'en':    'Interface2',
        'de':    'Interface2',
        'ru':    'Интерфейс2',
        'pt':    'Interface2',
        'nl':    'Interface2',
        'fr':    'Interface2',
        'es':    'Interface2',
        'pl':    'Interface2',
        'it':    'Interface2',
        'zh-cn': 'Interface2'
    },
    'Built-in Power Interface1':                                                      {
        'en':    'Built-in Power Interface 1',
        'de':    'Built-in Power Interface 1',
        'ru':    'Встроенное питание интерфейса1',
        'pt':    'Built-in Power Interface 1',
        'nl':    'Built-in Power Interface 1',
        'fr':    'Built-in Power Interface 1',
        'es':    'Built-in Power Interface 1',
        'pl':    'Built-in Power Interface 1',
        'it':    'Built-in Power Interface 1',
        'zh-cn': 'Built-in Power Interface 1'
    },
    'PCE control':                                                                    {
        'en':    'PCE control',
        'de':    'PCE control',
        'ru':    'Контроль ПКЭ',
        'pt':    'PCE control',
        'nl':    'PCE control',
        'fr':    'PCE control',
        'es':    'PCE control',
        'pl':    'PCE control',
        'it':    'PCE control',
        'zh-cn': 'PCE control'
    },
    'Phase energy metering A+':                                                       {
        'en':    'Phase energy metering A +',
        'de':    'Phase energy metering A +',
        'ru':    'Пофазный учет энергии А+',
        'pt':    'Phase energy metering A +',
        'nl':    'Phase energy metering A +',
        'fr':    'Phase energy metering A +',
        'es':    'Phase energy metering A +',
        'pl':    'Phase energy metering A +',
        'it':    'Phase energy metering A +',
        'zh-cn': 'Phase energy metering A +'
    },
    'Integrated PLC2 Modem':                                                          {
        'en':    'Integrated PLC2 Modem',
        'de':    'Integrated PLC2 Modem',
        'ru':    'Встроенный модем PLC2',
        'pt':    'Integrated PLC2 Modem',
        'nl':    'Integrated PLC2 Modem',
        'fr':    'Integrated PLC2 Modem',
        'es':    'Integrated PLC2 Modem',
        'pl':    'Integrated PLC2 Modem',
        'it':    'Integrated PLC2 Modem',
        'zh-cn': 'Integrated PLC2 Modem'
    },
    'Profile2':                                                                       {
        'en':    'Profile2',
        'de':    'Profile2',
        'ru':    'Профиль2',
        'pt':    'Profile2',
        'nl':    'Profile2',
        'fr':    'Profile2',
        'es':    'Profile2',
        'pl':    'Profile2',
        'it':    'Profile2',
        'zh-cn': 'Profile2'
    },
    'Modular compartment electronic seal':                                            {
        'en':    'Modular compartment electronic seal',
        'de':    'Modular compartment electronic seal',
        'ru':    'Электронная пломба модульного отсека',
        'pt':    'Modular compartment electronic seal',
        'nl':    'Modular compartment electronic seal',
        'fr':    'Modular compartment electronic seal',
        'es':    'Modular compartment electronic seal',
        'pl':    'Modular compartment electronic seal',
        'it':    'Modular compartment electronic seal',
        'zh-cn': 'Modular compartment electronic seal'
    },
    'Tariff switching by external voltage':                                           {
        'en':    'Tariff switching by external voltage',
        'de':    'Tariff switching by external voltage',
        'ru':    'Перекл. тарифов внешн. напр.',
        'pt':    'Tariff switching by external voltage',
        'nl':    'Tariff switching by external voltage',
        'fr':    'Tariff switching by external voltage',
        'es':    'Tariff switching by external voltage',
        'pl':    'Tariff switching by external voltage',
        'it':    'Tariff switching by external voltage',
        'zh-cn': 'Tariff switching by external voltage'
    },
    'Voltage transformation ratio':                                                   {
        'en':    'Voltage transformation ratio',
        'de':    'Voltage transformation ratio',
        'ru':    'Коэф. трансформации по напряжению',
        'pt':    'Voltage transformation ratio',
        'nl':    'Voltage transformation ratio',
        'fr':    'Voltage transformation ratio',
        'es':    'Voltage transformation ratio',
        'pl':    'Voltage transformation ratio',
        'it':    'Voltage transformation ratio',
        'zh-cn': 'Voltage transformation ratio'
    },
    'Current transformer ratio':                                                      {
        'en':    'Current transformer ratio',
        'de':    'Current transformer ratio',
        'ru':    'Коэф. трансформации по току',
        'pt':    'Current transformer ratio',
        'nl':    'Current transformer ratio',
        'fr':    'Current transformer ratio',
        'es':    'Current transformer ratio',
        'pl':    'Current transformer ratio',
        'it':    'Current transformer ratio',
        'zh-cn': 'Current transformer ratio'
    },
    'cosfTotal':                                                                      {
        'en':    'Power factor average',
        'de':    'Power factor average',
        'ru':    'Коэффициент мощности средний',
        'pt':    'Power factor average',
        'nl':    'Power factor average',
        'fr':    'Power factor average',
        'es':    'Power factor average',
        'pl':    'Power factor average',
        'it':    'Power factor average',
        'zh-cn': 'Power factor average'
    }
};

/*          totalEnergyActivePlus:          {val: null, desc: 'Общая энергия от сброса A+'},
            totalEnergyActiveMinus:         {val: null, desc: 'Общая энергия от сброса A-'},
            totalEnergyReactivePlus:        {val: null, desc: 'Общая энергия от сброса R+'},
            totalEnergyReactiveMinus:       {val: null, desc: 'Общая энергия от сброса R-'},
            totalEnergy:                    {val: null, desc: 'Общая энергия'},
            currentYearEnergyActivePlus:    {val: null, desc: 'Энергия за текущий год A+'},
            currentYearEnergyActiveMinus:   {val: null, desc: 'Энергия за текущий год A-'},
            currentYearEnergyReactivePlus:  {val: null, desc: 'Энергия за текущий год R+'},
            currentYearEnergyReactiveMinus: {val: null, desc: 'Энергия за текущий год R-'},
            currentYearEnergyTotal:         {val: null, desc: 'Энергия за текущий'},
            currentDayEnergyActivePlus:     {val: null, desc: 'Энергия за текущий день A+'},
            currentDayEnergyActiveMinus:    {val: null, desc: 'Энергия за текущий день A-'},
            currentDayEnergyReactivePlus:   {val: null, desc: 'Энергия за текущий день R+'},
            currentDayEnergyReactiveMinus:  {val: null, desc: 'Энергия за текущий день R-'},
            currentDayEnergyTotal:          {val: null, desc: 'Энергия за текущий'},
            oneTarrifEnergyActivePlus:      {val: null, desc: 'Энергия по 1 тарифу активная прямая'},
            oneTarrifEnergyActiveMinus:     {val: null, desc: 'Энергия по 1 тарифу активная обратная'},
            oneTarrifEnergyReactivePlus:    {val: null, desc: 'Энергия по 1 тарифу реактивная прямая'},
            oneTarrifEnergyReactiveMinus:   {val: null, desc: 'Энергия по 1 тарифу реактивная обратная'},
            oneTarrifEnergyTotal:           {val: null, desc: 'Энергия по 1 тарифу'},
            twoTarrifEnergyActivePlus:      {val: null, desc: 'Энергия по 2 тарифу активная прямая'},
            twoTarrifEnergyActiveMinus:     {val: null, desc: 'Энергия по 2 тарифу активная обратная'},
            twoTarrifEnergyReactivePlus:    {val: null, desc: 'Энергия по 2 тарифу реактивная прямая'},
            twoTarrifEnergyReactiveMinus:   {val: null, desc: 'Энергия по 2 тарифу реактивная обратная'},
            twoTarrifEnergyTotal:           {val: null, desc: 'Энергия по 2 тарифу'},
            threeTarrifEnergyActivePlus:    {val: null, desc: 'Энергия по 3 тарифу активная прямая'},
            threeTarrifEnergyActiveMinus:   {val: null, desc: 'Энергия по 3 тарифу активная обратная'},
            threeTarrifEnergyReactivePlus:  {val: null, desc: 'Энергия по 3 тарифу реактивная прямая'},
            threeTarrifEnergyReactiveMinus: {val: null, desc: 'Энергия по 3 тарифу реактивная обратная'},
            threeTarrifEnergyTotal:         {val: null, desc: 'Энергия по 3 тарифу'},
            fourTarrifEnergyActivePlus:     {val: null, desc: 'Энергия по 4 тарифу активная прямая'},
            fourTarrifEnergyActiveMinus:    {val: null, desc: 'Энергия по 4 тарифу активная обратная'},
            fourTarrifEnergyReactivePlus:   {val: null, desc: 'Энергия по 4 тарифу реактивная прямая'},
            fourTarrifEnergyReactiveMinus:  {val: null, desc: 'Энергия по 4 тарифу реактивная обратная'},
            fourTarrifEnergyTotal:          {val: null, desc: 'Энергия по 4 тарифу'},
            powerTotal:                     {val: null, desc: 'Мощность общая'},
            powerPhase1:                    {val: null, desc: 'Мощность на 1 фазе'},
            powerPhase2:                    {val: null, desc: 'Мощность на 2 фазе'},
            powerPhase3:                    {val: null, desc: 'Мощность на 3 фазе'},
            voltagePhase1:                  {val: null, desc: 'Напряжение 1 фазы'},
            voltagePhase2:                  {val: null, desc: 'Напряжение 2 фазы'},
            voltagePhase3:                  {val: null, desc: 'Напряжение 3 фазы'},
            currentPhase1:                  {val: null, desc: 'Ток 1 фазы'},
            currentPhase2:                  {val: null, desc: 'Ток 2 фазы'},
            currentPhase3:                  {val: null, desc: 'Ток 3 фазы'},
            //cosfTotal:                      {val: null, desc: 'Коэффициент мощности средний'},
            cosfPhase1:                     {val: null, desc: 'Коэффициент мощности по 1 фазе'},
            cosfPhase2:                     {val: null, desc: 'Коэффициент мощности по 2 фазе'},
            cosfPhase3:                     {val: null, desc: 'Коэффициент мощности по 3 фазе'},*/
