/*global systemDictionary:true */
'use strict';
systemDictionary = {
    'mercury adapter':                                                                {
        'en':    'Adapter settings for mercury',
        'de':    'Adaptereinstellungen für mercury',
        'ru':    'Настройки адаптера mercury',
        'pt':    'Configurações do adaptador para mercury',
        'nl':    'Adapterinstellingen voor mercury',
        'fr':    "Paramètres d'adaptateur pour mercury",
        'it':    "Impostazioni dell'adattatore per mercury",
        'es':    'Ajustes del adaptador para mercury',
        'pl':    'Ustawienia adaptera dla mercury',
        'zh-cn': 'mercury的适配器设置'
    },
    'devices':                                                                        {
        'en':    'Devices',
        'de':    'Devices',
        'ru':    'Устройства',
        'pt':    'Devices',
        'nl':    'Devices',
        'fr':    'Devices',
        'it':    'Devices',
        'es':    'Devices',
        'pl':    'Devices',
        'zh-cn': 'Devices'
    },
    'settings':                                                                       {
        'en':    'Settings',
        'de':    'Settings',
        'ru':    'Настройки',
        'pt':    'Settings',
        'nl':    'Settings',
        'fr':    'Settings',
        'it':    'Settings',
        'es':    'Settings',
        'pl':    'Settings',
        'zh-cn': 'Settings'
    },
    'typeconnect':                                                                    {
        'en':    'Connection type',
        'de':    'Connection type',
        'ru':    'Тип соединения',
        'pt':    'Connection type',
        'nl':    'Connection type',
        'fr':    'Connection type',
        'it':    'Connection type',
        'es':    'Connection type',
        'pl':    'Connection type',
        'zh-cn': 'Connection type'
    },
    'ip':                                                                             {
        'en':    'IP address',
        'de':    'IP address',
        'ru':    'IP адрес',
        'pt':    'IP address',
        'nl':    'IP address',
        'fr':    'IP address',
        'it':    'IP address',
        'es':    'IP address',
        'pl':    'IP address',
        'zh-cn': 'IP address'
    },
    'tcpport':                                                                        {
        'en':    'Port',
        'de':    'Port',
        'ru':    'Порт',
        'pt':    'Port',
        'nl':    'Port',
        'fr':    'Port',
        'it':    'Port',
        'es':    'Port',
        'pl':    'Port',
        'zh-cn': 'Port'
    },
    'tcp':                                                                            {
        'en':    'TCP/IP',
        'de':    'TCP/IP',
        'ru':    'TCP/IP',
        'pt':    'TCP/IP',
        'nl':    'TCP/IP',
        'fr':    'TCP/IP',
        'it':    'TCP/IP',
        'es':    'TCP/IP',
        'pl':    'TCP/IP',
        'zh-cn': 'TCP/IP'
    },
    'usb':                                                                            {
        'en':    'USB/COM',
        'de':    'USB/COM',
        'ru':    'USB/COM',
        'pt':    'USB/COM',
        'nl':    'USB/COM',
        'fr':    'USB/COM',
        'it':    'USB/COM',
        'es':    'USB/COM',
        'pl':    'USB/COM',
        'zh-cn': 'USB/COM'
    },
    'baud':                                                                           {
        'en':    'Baudrate',
        'de':    'Baudrate',
        'ru':    'Скорость передачи данных',
        'pt':    'Baudrate',
        'nl':    'Baudrate',
        'fr':    'Baudrate',
        'it':    'Baudrate',
        'es':    'Baudrate',
        'pl':    'Baudrate',
        'zh-cn': 'Baudrate'
    },
    'usbport':                                                                        {
        'en':    'COM port',
        'de':    'COM port',
        'ru':    'Номер COM порта',
        'pt':    'COM port',
        'nl':    'COM port',
        'fr':    'COM port',
        'it':    'COM port',
        'es':    'COM port',
        'pl':    'COM port',
        'zh-cn': 'COM port'
    },
    'parity':                                                                         {
        'en':    'Parity',
        'de':    'Parity',
        'ru':    'Четность',
        'pt':    'Parity',
        'nl':    'Parity',
        'fr':    'Parity',
        'it':    'Parity',
        'es':    'Parity',
        'pl':    'Parity',
        'zh-cn': 'Parity'
    },
    'timeoutresponse':                                                                {
        'en':    'Response Timeout (ms)',
        'de':    'Response Timeout (ms)',
        'ru':    'Время ожидания ответа (мс)',
        'pt':    'Response Timeout (ms)',
        'nl':    'Response Timeout (ms)',
        'fr':    'Response Timeout (ms)',
        'it':    'Response Timeout (ms)',
        'es':    'Response Timeout (ms)',
        'pl':    'Response Timeout (ms)',
        'zh-cn': 'Response Timeout (ms)'
    },
    'systemtimeout':                                                                  {
        'en':    'System Timeout (ms)',
        'de':    'System Timeout (ms)',
        'ru':    'Системный таймаут (мс)',
        'pt':    'System Timeout (ms)',
        'nl':    'System Timeout (ms)',
        'fr':    'System Timeout (ms)',
        'it':    'System Timeout (ms)',
        'es':    'System Timeout (ms)',
        'pl':    'System Timeout (ms)',
        'zh-cn': 'System Timeout (ms)'
    },
    'factortimeout':                                                                  {
        'en':    'System Timeout Multiplier',
        'de':    'System Timeout Multiplier',
        'ru':    'Множитель системного таймаута',
        'pt':    'System Timeout Multiplier',
        'nl':    'System Timeout Multiplier',
        'fr':    'System Timeout Multiplier',
        'it':    'System Timeout Multiplier',
        'es':    'System Timeout Multiplier',
        'pl':    'System Timeout Multiplier',
        'zh-cn': 'System Timeout Multiplier'
    },
    'model':                                                                          {
        'en':    'Counter model',
        'de':    'v',
        'ru':    'Модель счетчика',
        'pt':    'Counter model',
        'nl':    'Counter model',
        'fr':    'Counter model',
        'it':    'Counter model',
        'es':    'Counter model',
        'pl':    'Counter model',
        'zh-cn': 'Counter model'
    },
    'address':                                                                        {
        'en':    'Counter network address',
        'de':    'Counter network address',
        'ru':    'Сетевой адрес счетчика',
        'pt':    'Counter network address',
        'nl':    'Counter network address',
        'fr':    'Counter network address',
        'it':    'Counter network address',
        'es':    'Counter network address',
        'pl':    'Counter network address',
        'zh-cn': 'Counter network address'
    },
    'user':                                                                           {
        'en':    'User',
        'de':    'User',
        'ru':    'Пользователь',
        'pt':    'User',
        'nl':    'User',
        'fr':    'User',
        'it':    'User',
        'es':    'User',
        'pl':    'User',
        'zh-cn': 'User'
    },
    'admin':                                                                          {
        'en':    'Administrator',
        'de':    'Administrator',
        'ru':    'Администратор',
        'pt':    'Administrator',
        'nl':    'Administrator',
        'fr':    'Administrator',
        'it':    'Administrator',
        'es':    'Administrator',
        'pl':    'Administrator',
        'zh-cn': 'Administrator'
    },
    'password':                                                                       {
        'en':    'Password',
        'de':    'Password',
        'ru':    'Пароль',
        'pt':    'Password',
        'nl':    'Password',
        'fr':    'Password',
        'it':    'Password',
        'es':    'Password',
        'pl':    'Password',
        'zh-cn': 'Password'
    },
    'name':                                                                           {
        'en':    'Name',
        'de':    'Name',
        'ru':    'Имя',
        'pt':    'Name',
        'nl':    'Name',
        'fr':    'Name',
        'it':    'Name',
        'es':    'Name',
        'pl':    'Name',
        'zh-cn': 'Name'
    },
    'cancel':                                                                         {
        'en':    'Cancel',
        'de':    'Cancel',
        'ru':    'Отмена',
        'pt':    'Cancel',
        'nl':    'Cancel',
        'fr':    'Cancel',
        'it':    'Cancel',
        'es':    'Cancel',
        'pl':    'Cancel',
        'zh-cn': 'Cancel'
    },
    'agree':                                                                          {
        'en':    'OK',
        'de':    'OK',
        'ru':    'OK',
        'pt':    'OK',
        'nl':    'OK',
        'fr':    'OK',
        'it':    'OK',
        'es':    'OK',
        'pl':    'OK',
        'zh-cn': 'OK'
    },
    'find':                                                                           {
        'en':    'Find',
        'de':    'Find',
        'ru':    'Найти',
        'pt':    'Find',
        'nl':    'Find',
        'fr':    'Find',
        'it':    'Find',
        'es':    'Find',
        'pl':    'Find',
        'zh-cn': 'Find'
    },
    'info':                                                                           {
        'en':    'Information',
        'de':    'Information',
        'ru':    'Информация',
        'pt':    'Information',
        'nl':    'Information',
        'fr':    'Information',
        'it':    'Information',
        'es':    'Information',
        'pl':    'Information',
        'zh-cn': 'Information'
    },
    'input addres or sn':                                                             {
        'en':    'Enter counter address or serial number',
        'de':    'Enter counter address or serial number',
        'ru':    'Введите адрес или серийный номер счетчика',
        'pt':    'Enter counter address or serial number',
        'nl':    'Enter counter address or serial number',
        'fr':    'Enter counter address or serial number',
        'it':    'Enter counter address or serial number',
        'es':    'Enter counter address or serial number',
        'pl':    'Enter counter address or serial number',
        'zh-cn': 'Enter counter address or serial number'
    },
    'add counter':                                                                    {
        'en':    'Add counter',
        'de':    'Add counter',
        'ru':    'Добавить счетчик',
        'pt':    'Add counter',
        'nl':    'Add counter',
        'fr':    'Add counter',
        'it':    'Add counter',
        'es':    'Add counter',
        'pl':    'Add counter',
        'zh-cn': 'Add counter'
    },
    'Error':                                                                          {
        'en':    'Error',
        'de':    'Error',
        'ru':    'Ошибка',
        'pt':    'Error',
        'nl':    'Error',
        'fr':    'Error',
        'it':    'Error',
        'es':    'Error',
        'pl':    'Error',
        'zh-cn': 'Error'
    },
    'extended':                                                                       {
        'en':    'Extended Answer Mode',
        'de':    'Extended Answer Mode',
        'ru':    'Расширенный режим ответа',
        'pt':    'Extended Answer Mode',
        'nl':    'Extended Answer Mode',
        'fr':    'Extended Answer Mode',
        'it':    'Extended Answer Mode',
        'es':    'Extended Answer Mode',
        'pl':    'Extended Answer Mode',
        'zh-cn': 'Extended Answer Mode'
    },
    'addres or sn':                                                                   {
        'en':    'Address or Serial Number',
        'de':    'Address or Serial Number',
        'ru':    'Адрес или серийный номер',
        'pt':    'Address or Serial Number',
        'nl':    'Address or Serial Number',
        'fr':    'Address or Serial Number',
        'it':    'Address or Serial Number',
        'es':    'Address or Serial Number',
        'pl':    'Address or Serial Number',
        'zh-cn': 'Address or Serial Number'
    },
    'pollingtime':                                                                    {
        'en':    'Polling period (sec)',
        'de':    'Polling period (sec)',
        'ru':    'Период опроса (сек.)',
        'pt':    'Polling period (sec)',
        'nl':    'Polling period (sec)',
        'fr':    'Polling period (sec)',
        'it':    'Polling period (sec)',
        'es':    'Polling period (sec)',
        'pl':    'Polling period (sec)',
        'zh-cn': 'Polling period (sec)'
    },
    'delete the device':                                                              {
        'en':    'Are you sure you want to delete the device?',
        'de':    'Are you sure you want to delete the device?',
        'ru':    'Вы действительно хотите удалить устройство?',
        'pt':    'Are you sure you want to delete the device?',
        'nl':    'Are you sure you want to delete the device?',
        'fr':    'Are you sure you want to delete the device?',
        'it':    'Are you sure you want to delete the device?',
        'es':    'Are you sure you want to delete the device?',
        'pl':    'Are you sure you want to delete the device?',
        'zh-cn': 'Are you sure you want to delete the device?'
    },
    'counter card settings':                                                          {
        'en':    'Counter Card Settings',
        'de':    'Counter Card Settings',
        'ru':    'Настройки карточки счетчика',
        'pt':    'Counter Card Settings',
        'nl':    'Counter Card Settings',
        'fr':    'Counter Card Settings',
        'it':    'Counter Card Settings',
        'es':    'Counter Card Settings',
        'pl':    'Counter Card Settings',
        'zh-cn': 'Counter Card Settings'
    },
    'driver is not running':                                                          {
        'en':    'The driver is not running, first run the driver',
        'de':    'The driver is not running, first run the driver',
        'ru':    'Драйвер не запущен, сначала запустите драйвер',
        'pt':    'The driver is not running, first run the driver',
        'nl':    'The driver is not running, first run the driver',
        'fr':    'The driver is not running, first run the driver',
        'it':    'The driver is not running, first run the driver',
        'es':    'The driver is not running, first run the driver',
        'pl':    'The driver is not running, first run the driver',
        'zh-cn': 'The driver is not running, first run the driver'
    },
    'No response, retry the request':                                                 {
        'en':    'No response, retry the request',
        'de':    'No response, retry the request',
        'ru':    'Нет ответа, повторите запрос',
        'pt':    'No response, retry the request',
        'nl':    'No response, retry the request',
        'fr':    'No response, retry the request',
        'it':    'No response, retry the request',
        'es':    'No response, retry the request',
        'pl':    'No response, retry the request',
        'zh-cn': 'No response, retry the request'
    },
    'Error opening communication channel':                                            {
        'en':    'Error opening communication channel',
        'de':    'Error opening communication channel',
        'ru':    'Ошибка отрытия канала связи',
        'pt':    'Error opening communication channel',
        'nl':    'Error opening communication channel',
        'fr':    'Error opening communication channel',
        'it':    'Error opening communication channel',
        'es':    'Error opening communication channel',
        'pl':    'Error opening communication channel',
        'zh-cn': 'Error opening communication channel'
    },
    'Invalid data specified':                                                         {
        'en':    'Invalid data specified',
        'de':    'Invalid data specified',
        'ru':    'Заданы не корректные данные',
        'pt':    'Invalid data specified',
        'nl':    'Invalid data specified',
        'fr':    'Invalid data specified',
        'it':    'Invalid data specified',
        'es':    'Invalid data specified',
        'pl':    'Invalid data specified',
        'zh-cn': 'Invalid data specified'
    },
    'No response':                                                                    {
        'en':    'No response',
        'de':    'No response',
        'ru':    'Нет ответа',
        'pt':    'No response',
        'nl':    'No response',
        'fr':    'No response',
        'it':    'No response',
        'es':    'No response',
        'pl':    'No response',
        'zh-cn': 'No response'
    },
    'CRC Error':                                                                      {
        'en':    'CRC Error',
        'de':    'CRC Error',
        'ru':    'Ошибка котнтрольной сумме CRC',
        'pt':    'CRC Error',
        'nl':    'CRC Error',
        'fr':    'CRC Error',
        'it':    'CRC Error',
        'es':    'CRC Error',
        'pl':    'CRC Error',
        'zh-cn': 'CRC Error'
    },
    'Location':                                                                       {
        'en':    'Location',
        'de':    'Location',
        'ru':    'Местоположение',
        'pt':    'Location',
        'nl':    'Location',
        'fr':    'Location',
        'it':    'Location',
        'es':    'Location',
        'pl':    'Location',
        'zh-cn': 'Location'
    },
    'Serial number':                                                                  {
        'en':    'Serial number',
        'de':    'Serial number',
        'ru':    'Серийный номер',
        'pt':    'Serial number',
        'nl':    'Serial number',
        'fr':    'Serial number',
        'it':    'Serial number',
        'es':    'Serial number',
        'pl':    'Serial number',
        'zh-cn': 'Serial number'
    },
    'Production date':                                                                {
        'en':    'Production date',
        'de':    'Production date',
        'ru':    'Дата изготовления',
        'pt':    'Production date',
        'nl':    'Production date',
        'fr':    'Production date',
        'it':    'Production date',
        'es':    'Production date',
        'pl':    'Production date',
        'zh-cn': 'Production date'
    },
    'Software version':                                                               {
        'en':    'Software version',
        'de':    'Software version',
        'ru':    'Версия ПО',
        'pt':    'Software version',
        'nl':    'Software version',
        'fr':    'Software version',
        'it':    'Software version',
        'es':    'Software version',
        'pl':    'Software version',
        'zh-cn': 'Software version'
    },
    'Everything is fine':                                                             {
        'en':    'Everything is fine',
        'de':    'Everything is fine',
        'ru':    'Все нормально',
        'pt':    'Everything is fine',
        'nl':    'Everything is fine',
        'fr':    'Everything is fine',
        'it':    'Everything is fine',
        'es':    'Everything is fine',
        'pl':    'Everything is fine',
        'zh-cn': 'Everything is fine'
    },
    'Invalid command or parameter':                                                   {
        'en':    'Invalid command or parameter ',
        'de':    'Invalid command or parameter ',
        'ru':    'Недопустимая команда или параметр',
        'pt':    'Invalid command or parameter ',
        'nl':    'Invalid command or parameter ',
        'fr':    'Invalid command or parameter ',
        'it':    'Invalid command or parameter ',
        'es':    'Invalid command or parameter ',
        'pl':    'Invalid command or parameter ',
        'zh-cn': 'Invalid command or parameter '
    },
    'Not enough level to satisfy request':                                            {
        'en':    'Not enough level to satisfy request',
        'de':    'Not enough level to satisfy request',
        'ru':    'Недостаточен уровень для удовлетворения запроса',
        'pt':    'Not enough level to satisfy request',
        'nl':    'Not enough level to satisfy request',
        'fr':    'Not enough level to satisfy request',
        'it':    'Not enough level to satisfy request',
        'es':    'Not enough level to satisfy request',
        'pl':    'Not enough level to satisfy request',
        'zh-cn': 'Not enough level to satisfy request'
    },
    'The counter’s internal clock has already been adjusted during the current day.': {
        'en':    'The counter’s internal clock has already been adjusted during the current day.',
        'de':    'The counter’s internal clock has already been adjusted during the current day.',
        'ru':    'Внутренние часы счетчика уже корректировались в течение текущих суток',
        'pt':    'The counter’s internal clock has already been adjusted during the current day.',
        'nl':    'The counter’s internal clock has already been adjusted during the current day.',
        'fr':    'The counter’s internal clock has already been adjusted during the current day.',
        'it':    'The counter’s internal clock has already been adjusted during the current day.',
        'es':    'The counter’s internal clock has already been adjusted during the current day.',
        'pl':    'The counter’s internal clock has already been adjusted during the current day.',
        'zh-cn': 'The counter’s internal clock has already been adjusted during the current day.'
    },
    'Communication channel not open, try again later':                                {
        'en':    'Communication channel not open, try again later',
        'de':    'Communication channel not open, try again later',
        'ru':    'Не открыт канал связи, повторите попытку позже',
        'pt':    'Communication channel not open, try again later',
        'nl':    'Communication channel not open, try again later',
        'fr':    'Communication channel not open, try again later',
        'it':    'Communication channel not open, try again later',
        'es':    'Communication channel not open, try again later',
        'pl':    'Communication channel not open, try again later',
        'zh-cn': 'Communication channel not open, try again later'
    },
    'CRC16 software':                                                                 {
        'en':    'CRC16 software CRC16 ПО прибора',
        'de':    'CRC16 software CRC16 ПО прибора',
        'ru':    'CRC16 ПО прибора',
        'pt':    'CRC16 software CRC16 ПО прибора',
        'nl':    'CRC16 software CRC16 ПО прибора',
        'fr':    'CRC16 software CRC16 ПО прибора',
        'es':    'CRC16 software CRC16 ПО прибора',
        'pl':    'CRC16 software CRC16 ПО прибора',
        'it':    'CRC16 software CRC16 ПО прибора',
        'zh-cn': 'CRC16 software CRC16 ПО прибора'
    },
    'Energy Class A+':                                                                {
        'en':    'Energy Class A + Класс энергии A+',
        'de':    'Energy Class A + Класс энергии A+',
        'ru':    'Класс энергии A+',
        'pt':    'Energy Class A + Класс энергии A+',
        'nl':    'Energy Class A + Класс энергии A+',
        'fr':    'Energy Class A + Класс энергии A+',
        'es':    'Energy Class A + Класс энергии A+',
        'pl':    'Energy Class A + Класс энергии A+',
        'it':    'Energy Class A + Класс энергии A+',
        'zh-cn': 'Energy Class A + Класс энергии A+'
    },
    'Energy Class R+':                                                                {
        'en':    'Energy Class R+',
        'de':    'Energy Class R+',
        'ru':    'Класс энергии R+',
        'pt':    'Energy Class R+',
        'nl':    'Energy Class R+',
        'fr':    'Energy Class R+',
        'es':    'Energy Class R+',
        'pl':    'Energy Class R+',
        'it':    'Energy Class R+',
        'zh-cn': 'Energy Class R+'
    },
    'Rated voltage':                                                                  {
        'en':    'Rated voltage Номинальное напряжение',
        'de':    'Rated voltage Номинальное напряжение',
        'ru':    'Номинальное напряжение',
        'pt':    'Rated voltage Номинальное напряжение',
        'nl':    'Rated voltage Номинальное напряжение',
        'fr':    'Rated voltage Номинальное напряжение',
        'es':    'Rated voltage Номинальное напряжение',
        'pl':    'Rated voltage Номинальное напряжение',
        'it':    'Rated voltage Номинальное напряжение',
        'zh-cn': 'Rated voltage Номинальное напряжение'
    },
    'Rated current':                                                                  {
        'en':    'Rated current Номинальный ток',
        'de':    'Rated current Номинальный ток',
        'ru':    'Номинальный ток',
        'pt':    'Rated current Номинальный ток',
        'nl':    'Rated current Номинальный ток',
        'fr':    'Rated current Номинальный ток',
        'es':    'Rated current Номинальный ток',
        'pl':    'Rated current Номинальный ток',
        'it':    'Rated current Номинальный ток',
        'zh-cn': 'Rated current Номинальный ток'
    },
    'Number of destinations':                                                         {
        'en':    'Number of destinations Число направлений',
        'de':    'Number of destinations Число направлений',
        'ru':    'Число направлений',
        'pt':    'Number of destinations Число направлений',
        'nl':    'Number of destinations Число направлений',
        'fr':    'Number of destinations Число направлений',
        'es':    'Number of destinations Число направлений',
        'pl':    'Number of destinations Число направлений',
        'it':    'Number of destinations Число направлений',
        'zh-cn': 'Number of destinations Число направлений'
    },
    'Temperature Range':                                                              {
        'en':    'Temperature Range Температурный диапазон',
        'de':    'Temperature Range Температурный диапазон',
        'ru':    'Температурный диапазон',
        'pt':    'Temperature Range Температурный диапазон',
        'nl':    'Temperature Range Температурный диапазон',
        'fr':    'Temperature Range Температурный диапазон',
        'es':    'Temperature Range Температурный диапазон',
        'pl':    'Temperature Range Температурный диапазон',
        'it':    'Temperature Range Температурный диапазон',
        'zh-cn': 'Temperature Range Температурный диапазон'
    },
    'Medium Capacity Profile capacities':                                             {
        'en':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'de':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'ru':    'Учет профиля сред. мощностей',
        'pt':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'nl':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'fr':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'es':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'pl':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'it':    'Medium Capacity Profile capacities Учет профиля сред. мощностей',
        'zh-cn': 'Medium Capacity Profile capacities Учет профиля сред. мощностей'
    },
    'Number of phases':                                                               {
        'en':    'Number of phases Число фаз',
        'de':    'Number of phases Число фаз',
        'ru':    'Число фаз',
        'pt':    'Number of phases Число фаз',
        'nl':    'Number of phases Число фаз',
        'fr':    'Number of phases Число фаз',
        'es':    'Number of phases Число фаз',
        'pl':    'Number of phases Число фаз',
        'it':    'Number of phases Число фаз',
        'zh-cn': 'Number of phases Число фаз'
    },
    'Counter constant':                                                               {
        'en':    'Counter constant Постоянная счетчика',
        'de':    'Counter constant Постоянная счетчика',
        'ru':    'Постоянная счетчика',
        'pt':    'Counter constant Постоянная счетчика',
        'nl':    'Counter constant Постоянная счетчика',
        'fr':    'Counter constant Постоянная счетчика',
        'es':    'Counter constant Постоянная счетчика',
        'pl':    'Counter constant Постоянная счетчика',
        'it':    'Counter constant Постоянная счетчика',
        'zh-cn': 'Counter constant Постоянная счетчика'
    },
    'Phase Summation':                                                                {
        'en':    'Phase Summation Суммирование фаз',
        'de':    'Phase Summation Суммирование фаз',
        'ru':    'Суммирование фаз',
        'pt':    'Phase Summation Суммирование фаз',
        'nl':    'Phase Summation Суммирование фаз',
        'fr':    'Phase Summation Суммирование фаз',
        'es':    'Phase Summation Суммирование фаз',
        'pl':    'Phase Summation Суммирование фаз',
        'it':    'Phase Summation Суммирование фаз',
        'zh-cn': 'Phase Summation Суммирование фаз'
    },
    'Tariff':                                                                         {
        'en':    'Tariff Тарификатор',
        'de':    'Tariff Тарификатор',
        'ru':    'Тарификатор',
        'pt':    'Tariff Тарификатор',
        'nl':    'Tariff Тарификатор',
        'fr':    'Tariff Тарификатор',
        'es':    'Tariff Тарификатор',
        'pl':    'Tariff Тарификатор',
        'it':    'Tariff Тарификатор',
        'zh-cn': 'Tariff Тарификатор'
    },
    'Counter type':                                                                   {
        'en':    'Counter type Тип счетчика',
        'de':    'Counter type Тип счетчика',
        'ru':    'Тип счетчика',
        'pt':    'Counter type Тип счетчика',
        'nl':    'Counter type Тип счетчика',
        'fr':    'Counter type Тип счетчика',
        'es':    'Counter type Тип счетчика',
        'pl':    'Counter type Тип счетчика',
        'it':    'Counter type Тип счетчика',
        'zh-cn': 'Counter type Тип счетчика'
    },
    'Execution option':                                                               {
        'en':    'Execution option Вариант исполнения',
        'de':    'Execution option Вариант исполнения',
        'ru':    'Вариант исполнения',
        'pt':    'Execution option Вариант исполнения',
        'nl':    'Execution option Вариант исполнения',
        'fr':    'Execution option Вариант исполнения',
        'es':    'Execution option Вариант исполнения',
        'pl':    'Execution option Вариант исполнения',
        'it':    'Execution option Вариант исполнения',
        'zh-cn': 'Execution option Вариант исполнения'
    },
    'Memory':                                                                         {
        'en':    'Memory Объем памяти',
        'de':    'Memory Объем памяти',
        'ru':    'Объем памяти',
        'pt':    'Memory Объем памяти',
        'nl':    'Memory Объем памяти',
        'fr':    'Memory Объем памяти',
        'es':    'Memory Объем памяти',
        'pl':    'Memory Объем памяти',
        'it':    'Memory Объем памяти',
        'zh-cn': 'Memory Объем памяти'
    },
    'Built-in PLM Modem':                                                             {
        'en':    'Built-in PLM Modem Встроенный модем PLM',
        'de':    'Built-in PLM Modem Встроенный модем PLM',
        'ru':    'Встроенный модем PLM',
        'pt':    'Built-in PLM Modem Встроенный модем PLM',
        'nl':    'Built-in PLM Modem Встроенный модем PLM',
        'fr':    'Built-in PLM Modem Встроенный модем PLM',
        'es':    'Built-in PLM Modem Встроенный модем PLM',
        'pl':    'Built-in PLM Modem Встроенный модем PLM',
        'it':    'Built-in PLM Modem Встроенный модем PLM',
        'zh-cn': 'Built-in PLM Modem Встроенный модем PLM'
    },
    'Built-in GSM Modem':                                                             {
        'en':    'Built-in GSM Modem Встроенный модем GSM',
        'de':    'Built-in GSM Modem Встроенный модем GSM',
        'ru':    'Встроенный модем GSM',
        'pt':    'Built-in GSM Modem Встроенный модем GSM',
        'nl':    'Built-in GSM Modem Встроенный модем GSM',
        'fr':    'Built-in GSM Modem Встроенный модем GSM',
        'es':    'Built-in GSM Modem Встроенный модем GSM',
        'pl':    'Built-in GSM Modem Встроенный модем GSM',
        'it':    'Built-in GSM Modem Встроенный модем GSM',
        'zh-cn': 'Built-in GSM Modem Встроенный модем GSM'
    },
    'Optical port':                                                                   {
        'en':    'Optical port Оптопорт',
        'de':    'Optical port Оптопорт',
        'ru':    'Оптопорт',
        'pt':    'Optical port Оптопорт',
        'nl':    'Optical port Оптопорт',
        'fr':    'Optical port Оптопорт',
        'es':    'Optical port Оптопорт',
        'pl':    'Optical port Оптопорт',
        'it':    'Optical port Оптопорт',
        'zh-cn': 'Optical port Оптопорт'
    },
    'Interface type':                                                                 {
        'en':    'Interface type Тип интерфейса',
        'de':    'Interface type Тип интерфейса',
        'ru':    'Тип интерфейса',
        'pt':    'Interface type Тип интерфейса',
        'nl':    'Interface type Тип интерфейса',
        'fr':    'Interface type Тип интерфейса',
        'es':    'Interface type Тип интерфейса',
        'pl':    'Interface type Тип интерфейса',
        'it':    'Interface type Тип интерфейса',
        'zh-cn': 'Interface type Тип интерфейса'
    },
    'External power':                                                                 {
        'en':    'External power Внешнее питание',
        'de':    'External power Внешнее питание',
        'ru':    'Внешнее питание',
        'pt':    'External power Внешнее питание',
        'nl':    'External power Внешнее питание',
        'fr':    'External power Внешнее питание',
        'es':    'External power Внешнее питание',
        'pl':    'External power Внешнее питание',
        'it':    'External power Внешнее питание',
        'zh-cn': 'External power Внешнее питание'
    },
    'Top Seal Electronic Seal':                                                       {
        'en':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'de':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'ru':    'Элект. пломба верх. крышки',
        'pt':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'nl':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'fr':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'es':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'pl':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'it':    'Top Seal Electronic Seal Элект. пломба верх. крышки',
        'zh-cn': 'Top Seal Electronic Seal Элект. пломба верх. крышки'
    },
    'Built-in load shedding relay':                                                   {
        'en':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'de':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'ru':    'Встроен. реле отключ. нагруз.',
        'pt':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'nl':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'fr':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'es':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'pl':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'it':    'Built-in load shedding relay Встроен. реле отключ. нагруз.',
        'zh-cn': 'Built-in load shedding relay Встроен. реле отключ. нагруз.'
    },
    'LCD backlight':                                                                  {
        'en':    'LCD backlight Подсветка ЖКИ',
        'de':    'LCD backlight Подсветка ЖКИ',
        'ru':    'Подсветка ЖКИ',
        'pt':    'LCD backlight Подсветка ЖКИ',
        'nl':    'LCD backlight Подсветка ЖКИ',
        'fr':    'LCD backlight Подсветка ЖКИ',
        'es':    'LCD backlight Подсветка ЖКИ',
        'pl':    'LCD backlight Подсветка ЖКИ',
        'it':    'LCD backlight Подсветка ЖКИ',
        'zh-cn': 'LCD backlight Подсветка ЖКИ'
    },
    'Tariff metering of maximum power':                                               {
        'en':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'de':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'ru':    'Потариф. учет макс. мощности',
        'pt':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'nl':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'fr':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'es':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'pl':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'it':    'Tariff metering of maximum power Потариф. учет макс. мощности',
        'zh-cn': 'Tariff metering of maximum power Потариф. учет макс. мощности'
    },
    'Electronic seal of protective cover':                                            {
        'en':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'de':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'ru':    'Элект. пломба защит. крышки',
        'pt':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'nl':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'fr':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'es':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'pl':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'it':    'Electronic seal of protective cover Элект. пломба защит. крышки',
        'zh-cn': 'Electronic seal of protective cover Элект. пломба защит. крышки'
    },
    'Interface2':                                                                     {
        'en':    'Interface2 Интерфейс2',
        'de':    'Interface2 Интерфейс2',
        'ru':    'Интерфейс2',
        'pt':    'Interface2 Интерфейс2',
        'nl':    'Interface2 Интерфейс2',
        'fr':    'Interface2 Интерфейс2',
        'es':    'Interface2 Интерфейс2',
        'pl':    'Interface2 Интерфейс2',
        'it':    'Interface2 Интерфейс2',
        'zh-cn': 'Interface2 Интерфейс2'
    },
    'Built-in Power Interface1':                                                      {
        'en':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'de':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'ru':    'Встроен. питания интерфейса1',
        'pt':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'nl':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'fr':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'es':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'pl':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'it':    'Built-in Power Interface 1 Встроен. питания интерфейса1',
        'zh-cn': 'Built-in Power Interface 1 Встроен. питания интерфейса1'
    },
    'PCE control':                                                                    {
        'en':    'PCE control Контроль ПКЭ',
        'de':    'PCE control Контроль ПКЭ',
        'ru':    'Контроль ПКЭ',
        'pt':    'PCE control Контроль ПКЭ',
        'nl':    'PCE control Контроль ПКЭ',
        'fr':    'PCE control Контроль ПКЭ',
        'es':    'PCE control Контроль ПКЭ',
        'pl':    'PCE control Контроль ПКЭ',
        'it':    'PCE control Контроль ПКЭ',
        'zh-cn': 'PCE control Контроль ПКЭ'
    },
    'Phase energy metering A+':                                                       {
        'en':    'Phase energy metering A + Пофазный учет энергии А+',
        'de':    'Phase energy metering A + Пофазный учет энергии А+',
        'ru':    'Пофазный учет энергии А+',
        'pt':    'Phase energy metering A + Пофазный учет энергии А+',
        'nl':    'Phase energy metering A + Пофазный учет энергии А+',
        'fr':    'Phase energy metering A + Пофазный учет энергии А+',
        'es':    'Phase energy metering A + Пофазный учет энергии А+',
        'pl':    'Phase energy metering A + Пофазный учет энергии А+',
        'it':    'Phase energy metering A + Пофазный учет энергии А+',
        'zh-cn': 'Phase energy metering A + Пофазный учет энергии А+'
    },
    'Integrated PLC2 Modem':                                                          {
        'en':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'de':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'ru':    'Встроенный модем PLC2',
        'pt':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'nl':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'fr':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'es':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'pl':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'it':    'Integrated PLC2 Modem Встроенный модем PLC2',
        'zh-cn': 'Integrated PLC2 Modem Встроенный модем PLC2'
    },
    'Profile2':                                                                       {
        'en':    'Profile2 Профиль2',
        'de':    'Profile2 Профиль2',
        'ru':    'Профиль2',
        'pt':    'Profile2 Профиль2',
        'nl':    'Profile2 Профиль2',
        'fr':    'Profile2 Профиль2',
        'es':    'Profile2 Профиль2',
        'pl':    'Profile2 Профиль2',
        'it':    'Profile2 Профиль2',
        'zh-cn': 'Profile2 Профиль2'
    },
    'Modular compartment electronic seal':                                            {
        'en':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'de':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'ru':    'Элект. пломба модульного отсека',
        'pt':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'nl':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'fr':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'es':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'pl':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'it':    'Modular compartment electronic seal Элект. пломба модульного отсека',
        'zh-cn': 'Modular compartment electronic seal Элект. пломба модульного отсека'
    },
    'Tariff switching by external voltage':                                           {
        'en':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'de':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'ru':    'Перекл. тарифов внешн. напр.',
        'pt':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'nl':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'fr':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'es':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'pl':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'it':    'Tariff switching by external voltage Перекл. тарифов внешн. напр.',
        'zh-cn': 'Tariff switching by external voltage Перекл. тарифов внешн. напр.'
    },
    'Voltage transformation ratio':                                                   {
        'en':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'de':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'ru':    'Коэф. трансформации по напряжению',
        'pt':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'nl':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'fr':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'es':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'pl':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'it':    'Voltage transformation ratio Коэф. трансформации по напряжению',
        'zh-cn': 'Voltage transformation ratio Коэф. трансформации по напряжению'
    },
    'Current transformer ratio':                                                      {
        'en':    'Current transformer ratio Коэф. трансформации по току',
        'de':    'Current transformer ratio Коэф. трансформации по току',
        'ru':    'Коэф. трансформации по току',
        'pt':    'Current transformer ratio Коэф. трансформации по току',
        'nl':    'Current transformer ratio Коэф. трансформации по току',
        'fr':    'Current transformer ratio Коэф. трансформации по току',
        'es':    'Current transformer ratio Коэф. трансформации по току',
        'pl':    'Current transformer ratio Коэф. трансформации по току',
        'it':    'Current transformer ratio Коэф. трансформации по току',
        'zh-cn': 'Current transformer ratio Коэф. трансформации по току'
    }
};

/*totalEnergyActivePlus:          {val: null, desc: 'Общая энергия от сброса A+'},
            totalEnergyActiveMinus:         {val: null, desc: 'Общая энергия от сброса A-'},
            totalEnergyReactivePlus:        {val: null, desc: 'Общая энергия от сброса R+'},
            totalEnergyReactiveMinus:       {val: null, desc: 'Общая энергия от сброса R-'},
            totalEnergy:                    {val: null, desc: 'Общая энергия'},
            currentYearEnergyActivePlus:    {val: null, desc: 'Энергия за текущий год A+'},
            currentYearEnergyActiveMinus:   {val: null, desc: 'Энергия за текущий год A-'},
            currentYearEnergyReactivePlus:  {val: null, desc: 'Энергия за текущий год R+'},
            currentYearEnergyReactiveMinus: {val: null, desc: 'Энергия за текущий год R-'},
            currentYearEnergyTotal:         {val: null, desc: 'Энергия за текущий'},
            currentDayEnergyActivePlus:     {val: null, desc: 'Энергия за текущий день A+'},
            currentDayEnergyActiveMinus:    {val: null, desc: 'Энергия за текущий день A-'},
            currentDayEnergyReactivePlus:   {val: null, desc: 'Энергия за текущий день R+'},
            currentDayEnergyReactiveMinus:  {val: null, desc: 'Энергия за текущий день R-'},
            currentDayEnergyTotal:          {val: null, desc: 'Энергия за текущий'},
            oneTarrifEnergyActivePlus:      {val: null, desc: 'Энергия по 1 тарифу активная прямая'},
            oneTarrifEnergyActiveMinus:     {val: null, desc: 'Энергия по 1 тарифу активная обратная'},
            oneTarrifEnergyReactivePlus:    {val: null, desc: 'Энергия по 1 тарифу реактивная прямая'},
            oneTarrifEnergyReactiveMinus:   {val: null, desc: 'Энергия по 1 тарифу реактивная обратная'},
            oneTarrifEnergyTotal:           {val: null, desc: 'Энергия по 1 тарифу'},
            twoTarrifEnergyActivePlus:      {val: null, desc: 'Энергия по 2 тарифу активная прямая'},
            twoTarrifEnergyActiveMinus:     {val: null, desc: 'Энергия по 2 тарифу активная обратная'},
            twoTarrifEnergyReactivePlus:    {val: null, desc: 'Энергия по 2 тарифу реактивная прямая'},
            twoTarrifEnergyReactiveMinus:   {val: null, desc: 'Энергия по 2 тарифу реактивная обратная'},
            twoTarrifEnergyTotal:           {val: null, desc: 'Энергия по 2 тарифу'},
            threeTarrifEnergyActivePlus:    {val: null, desc: 'Энергия по 3 тарифу активная прямая'},
            threeTarrifEnergyActiveMinus:   {val: null, desc: 'Энергия по 3 тарифу активная обратная'},
            threeTarrifEnergyReactivePlus:  {val: null, desc: 'Энергия по 3 тарифу реактивная прямая'},
            threeTarrifEnergyReactiveMinus: {val: null, desc: 'Энергия по 3 тарифу реактивная обратная'},
            threeTarrifEnergyTotal:         {val: null, desc: 'Энергия по 3 тарифу'},
            fourTarrifEnergyActivePlus:     {val: null, desc: 'Энергия по 4 тарифу активная прямая'},
            fourTarrifEnergyActiveMinus:    {val: null, desc: 'Энергия по 4 тарифу активная обратная'},
            fourTarrifEnergyReactivePlus:   {val: null, desc: 'Энергия по 4 тарифу реактивная прямая'},
            fourTarrifEnergyReactiveMinus:  {val: null, desc: 'Энергия по 4 тарифу реактивная обратная'},
            fourTarrifEnergyTotal:          {val: null, desc: 'Энергия по 4 тарифу'},
            powerTotal:                     {val: null, desc: 'Мощность общая'},
            powerPhase1:                    {val: null, desc: 'Мощность по 1 фазе'},
            powerPhase2:                    {val: null, desc: 'Мощность по 2 фазе'},
            powerPhase3:                    {val: null, desc: 'Мощность по 3 фазе'},
            voltagePhase1:                  {val: null, desc: 'Напряжение 1 фазы'},
            voltagePhase2:                  {val: null, desc: 'Напряжение 2 фазы'},
            voltagePhase3:                  {val: null, desc: 'Напряжение 3 фазы'},
            currentPhase1:                  {val: null, desc: 'Ток 1 фазы'},
            currentPhase2:                  {val: null, desc: 'Ток 2 фазы'},
            currentPhase3:                  {val: null, desc: 'Ток 3 фазы'},
            cosfTotal:                      {val: null, desc: 'Коэффициент мощности средний'},
            cosfPhase1:                     {val: null, desc: 'Коэффициент мощности по 1 фазе'},
            cosfPhase2:                     {val: null, desc: 'Коэффициент мощности по 2 фазе'},
            cosfPhase3:                     {val: null, desc: 'Коэффициент мощности по 3 фазе'},*/